name: Akurmi Build XZ

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake make libtool gettext

      - name: Prepare the Build Environment
        run: |
          ./autogen.sh
          ./configure

      - name: Build
        run: make

      - name: Test (Optional)
        run: make check
