name: Build XZ with Harden-Runner

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_xz:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0

      # Install Autotools on Linux
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential po4a autopoint gcc-multilib doxygen musl-tools

      - name: configure
        run: ./configure
