name: Simple file events

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_xz:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int-sh
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      # Install Autotools on Linux
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential po4a autopoint gcc-multilib doxygen musl-tools

      - name: File Overwrite with mv
        run: |
         code='package main\n\nfunc main(){\nprintln("code added")\n}'
         printf "$code" > README1
         mv README1 README2
